apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: x4dmg59cg-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:e3822d9d7479cd62164a13de798a4b06e8c7e013@sha256:a6b1f8944e06b03391dc999f797ccbbd11c20f92754bec13b441a2b0f607d81c
          name: container-image
